 # 자동 실행
 on:
   push:
     branches:
       - "master"

 # 수동 실행      
 on:
   workflow_dispatch:
     inputs:
       logLevel:
         description: 'Log level'
         required: true
         default: 'warning'

 # 매주 월요일~금요일 KST+9 낮 12시에 실행 (UTC 03:00)
 on:
   schedule:
     - cron: '0 3 * * 1-5' 

jobs:
 deploy:
   name: Deploy
   runs-on: ubuntu-latest # 어떤 os 에서 실행시킬지
   environment: production

   steps:
   # Github에 저장된 코드를 CI 서버로 내려받아 뒷 step에서 사용할 수 있도록 하는 과정
   - name: Checkout
     uses: actions/checkout@v3

